series: Basic C++
title: C Strings
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Basics of C style strings and string manipulation in C++.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Basic C++
    title: Dynamically Allocated Arrays
