series: C++ IO
title: C Strings
author:
  name: David I. Schwartz, Ph.D.
  email: 
  github: https://github.com/IGME-RIT
description: A basic console application using string and iostream.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Basic C++
    title: Dynamically Allocated Arrays
